//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RED2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RED2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan again.
        /// </summary>
        internal static string btn_scan_again {
            get {
                return ResourceManager.GetString("btn_scan_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} empty directories (failed to delete: {1} dirs / protected: {2} / runtime: {3:D2}:{4:D2} min).
        /// </summary>
        internal static string delete_process_finished {
            get {
                return ResourceManager.GetString("delete_process_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete process was aborted..
        /// </summary>
        internal static string deletion_aborted {
            get {
                return ResourceManager.GetString("deletion_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the path you picked is not a directory or does not exist!.
        /// </summary>
        internal static string error_dir_does_not_exist {
            get {
                return ResourceManager.GetString("error_dir_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore file settings are in a bad format!.
        /// </summary>
        internal static string error_ignore_settings {
            get {
                return ResourceManager.GetString("error_ignore_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one folder can be accepted..
        /// </summary>
        internal static string error_only_one_folder {
            get {
                return ResourceManager.GetString("error_only_one_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} empty directories (checked {1} / runtime: {2:D2}:{3:D2} min).
        /// </summary>
        internal static string found_x_empty_folders {
            get {
                return ResourceManager.GetString("found_x_empty_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains &quot;trash&quot;.
        /// </summary>
        internal static string icon_contains_trash {
            get {
                return ResourceManager.GetString("icon_contains_trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string icon_default {
            get {
                return ResourceManager.GetString("icon_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string icon_deleted_folder {
            get {
                return ResourceManager.GetString("icon_deleted_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string icon_hidden_folder {
            get {
                return ResourceManager.GetString("icon_hidden_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string icon_locked_folder {
            get {
                return ResourceManager.GetString("icon_locked_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected.
        /// </summary>
        internal static string icon_protected_folder {
            get {
                return ResourceManager.GetString("icon_protected_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string icon_root {
            get {
                return ResourceManager.GetString("icon_root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string icon_warning {
            get {
                return ResourceManager.GetString("icon_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder that you want to be cleaned.
        /// </summary>
        internal static string please_select {
            get {
                return ResourceManager.GetString("please_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process was aborted..
        /// </summary>
        internal static string process_aborted {
            get {
                return ResourceManager.GetString("process_aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process was cancelled!.
        /// </summary>
        internal static string process_cancelled {
            get {
                return ResourceManager.GetString("process_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RED deleted {0} directories for you :).
        /// </summary>
        internal static string red_deleted {
            get {
                return ResourceManager.GetString("red_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting empty directories ({0}/{1})....
        /// </summary>
        internal static string removing_empty_folders {
            get {
                return ResourceManager.GetString("removing_empty_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning directories....
        /// </summary>
        internal static string scanning_folders {
            get {
                return ResourceManager.GetString("scanning_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching empty directories....
        /// </summary>
        internal static string searching_empty_folders {
            get {
                return ResourceManager.GetString("searching_empty_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started deletion process....
        /// </summary>
        internal static string started_deletion_process {
            get {
                return ResourceManager.GetString("started_deletion_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, do you really want to delete empty system directories?\nThis may harm your operating system..
        /// </summary>
        internal static string warning_really_delete {
            get {
                return ResourceManager.GetString("warning_really_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;{0}\&quot; folder skipped because creation time [{2}] is &lt; {1} hours old.
        /// </summary>
        internal static string young_folder_skipped {
            get {
                return ResourceManager.GetString("young_folder_skipped", resourceCulture);
            }
        }
    }
}
